name: Test
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - optionals: "sage, pplpy"
            packages: "sagelib=8.8 ppl pplpy"
          - optionals: "sage, pplpy"
            packages: "sagelib=8.9 ppl pplpy"
          - optionals: "sage, pplpy, mzv"
            packages: "sagelib=9.1 ppl pplpy"
          - optionals: "sage, pplpy, mzv, gmpxxyy, pyeantic, pyintervalxt, sage_flatsurf"
            packages: "sagelib=9.1 ppl pplpy sage-flatsurf pyflatsurf>=1.1.0 pyeantic>=1.1.1 pyintervalxt>=3.1.0"
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { mamba-version: "*", channels: "flatsurf,conda-forge", channel-priority: true }
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          mamba install --yes --quiet pip pytest pytest-xdist ipywidgets scipy matplotlib-base gap-defaults ${{ matrix.packages }}
          conda activate test
          conda list
      - name: Install surface-dynamics
        shell: bash -l {0}
        run: |
          pip install --verbose --no-index .
          # Show message about cppyy regenerating pre-compiled headers so it does not show during the tests
          python -c 'import cppyy' || true
      - name: Run SageMath doctests
        shell: bash -l {0}
        run: |
          export SURFACE_DYNAMICS_INSTALL="$(sage -c 'import surface_dynamics; print(surface_dynamics.__path__[0])')"
          sage -tp --force-lib --long --optional=${{ matrix.optionals }} ${SURFACE_DYNAMICS_INSTALL} doc
      - name: Run pytest
        shell: bash -l {0}
        run: pytest -n auto
      - name: Show logs
        run: grep "" /dev/null `find -name '*.log'` || true
        if: ${{ always() }}

env:
  MAKEFLAGS: -j2
  SAGE_NUM_THREADS: 2
